### ISSUE TITLE
Overflow errors due to UInt8 in CountIteratorDictionary?

### ISSUE THREAD

**Issue by robertfeldt** [matthieugomez/StringDistances.jl#12]
I see that you have switched to a dictionary-based count iterator. But how can it be safe to use UInt8s to count the number of occurrences of a q-gram? Since `UInt8(255)+UInt8(1) == UInt8(0)` this would mean that if one of the strings have more than 255 occurrences of one and the same q-gram all of the QGram distances will give the wrong result.

Maybe better to use the max num of q-grams in the strings (s1 and s2) to select how many bits of the UInt to use?

**Comment by matthieugomez** [comment]
Sorry, I have removed it. https://github.com/matthieugomez/StringDistances.jl/commit/a458b3356be5184ac5776ca95d166d8aabff82a0. I  experimented with it a bit but it did not have a big impact on perfomances.

**Comment by robertfeldt** [comment]
Ok, thanks.
