### ISSUE TITLE
Unicode error when using TokenMax() and Partial()

### ISSUE THREAD

**Issue by cdoool** [matthieugomez/StringDistances.jl#15]
Encountered an error when trying to compare a bunch of string in Chinese. This
`compare(TokenMax(RatcliffObershelp()), "为人子女者要堂堂正正做人，千万不可作奸犯科，致使父母蒙羞", "此前稍早些时候中国商务部发布消息称，中美经贸高级别磋商双方牵头人通话，中方就美拟9月1日加征关税进行了严正交涉。")`
or this
`compare(Partial(RatcliffObershelp()), "为人子女者要堂堂正正做人，千万不可作奸犯科，致使父母蒙羞", "此前稍早些时候中国商务部发布消息称，中美经贸高级别磋商双方牵头人通话，中方就美拟9月1日加征关税进行了严正交涉。")`
throw StringIndexError. At the same time, TokenSort, TokenSet or just plain RatcliffObershelp work just fine. Some relic from the times when StringDistances worked only with ASCII strings perhaps?

**Comment by matthieugomez** [comment]
Thanks for the report. This should be fixed by 
https://github.com/matthieugomez/StringDistances.jl/commit/dbf8a11d8e7650d06e1b7ee00240314e5a34a055
