### ISSUE TITLE
Define `result_type` for string distances

### ISSUE THREAD

**Issue by dillondaudert** [matthieugomez/StringDistances.jl#16]
I'd like to use `result_type` in a package that's supposed to work on arbitrary subtypes of `PreMetric`, but this isn't defined for any of the string distances here. It should be relatively straightforward to add, for reference: [Distances.jl](https://github.com/JuliaStats/Distances.jl/blob/master/src/metrics.jl#L259).

**Comment by matthieugomez** [comment]
Sure you’re welcome to add it!
