### ISSUE TITLE
Safe version of evaluate and compare for strings shorter than Q?

### ISSUE THREAD

**Issue by robertfeldt** [matthieugomez/StringDistances.jl#18]
when processing distances between pairs of a large number of strings I sometimes run into problems since `evaluate(Jaccard(2), "a", "b")` return `NaN`. Is this the "right" return value or should there be a "safe" version of evaluate that returns max distance (1.0) if the strings are not equal while returning min distance (0.0) if they are the same?

**Comment by matthieugomez** [comment]
I'm not sure what is the best way to handle this. One issue with
systematically defining a safe version is that max distance is not defined
for all distances.
So this safe version should also normalize distance.

But then, this is exactly what `compare` is for — it always returns
something between 0 and 1.
https://github.com/matthieugomez/StringDistances.jl/blob/master/src/compare.jl#L38

**Comment by robertfeldt** [comment]
Yeah, you're right, most distances have a min value but some don't have a max. So maybe I'll use `compare` instead...

**Comment by matthieugomez** [comment]
I have added a function `normalize` such that a normalized distance  always returns something between 0 and 1. 
```julia
julia> evaluate(Jaccard(2), "a", "b")
NaN
julia> evaluate(normalize(Jaccard(2)), "a", "b")
1.0
```
`compare` is just defined as 1 minus the normalized distance.
