### ISSUE TITLE
Operate on types other than strings

### ISSUE THREAD

**Issue by baggepinnen** [matthieugomez/StringDistances.jl#21]
Would it be posible to use this package to operate on vectors, e.g,
```
evaluate(Levenshtein(), [1,2,3], [1,2,10]) == 1 # They differ in one element
```
?

**Comment by matthieugomez** [comment]
Makes sense. I have just pushed a commit that allows any iterable for Jaro, Levenshtein, DamerauLevenstein, and QGramDistances
