### ISSUE TITLE
`compare` with `Partial` distances gives negative answers

### ISSUE THREAD

**Issue by ericphanson** [matthieugomez/StringDistances.jl#31]
```julia
julia> compare("ab", "de", Partial(DamerauLevenshtein()))
-1

julia> compare("abc", "de", Partial(DamerauLevenshtein()))
-1
```
This causes `findmax` to not work. I think this is due to the normalization changes. This also seems odd:

```julia
julia> normalize(Partial(DamerauLevenshtein()))("ab", "cde")
2

julia> normalize(Partial(DamerauLevenshtein()))("ab", "cdef")
2
```

**Comment by matthieugomez** [comment]
Ok, I had to go back to normalizing Partial/TokenSort/TokenSet, otherwise the package becomes too complicated for me.
I have added tests for your examples in 0.7.2

**Comment by ericphanson** [comment]
Ok, but this is a breaking change; I've updated my code + compat for 0.7 but I'll have to pin that release then to avoid hitting the normalized methods (at least until I can update again..).

By the way, I think `normalize` for `Partial` would be easy enough (just divide by the length of the smaller string), but I haven't looked at the others yet.

**Comment by matthieugomez** [comment]
Ok, then the new version is 0.8. The difficulty is not really about normalizing Partial, it's more about what to do with max_dist, which is not available for all distances.  `Normalizing` a distance always gives a default `max_dist = 1.0`, which makes it simpler.

**Comment by ericphanson** [comment]
Ok, 0.8 sounds good, thanks. That makes sense regarding `max_dist`, thanks for explaining.
