### ISSUE TITLE
DamerauLevenshtein() vs  Levenshtein() why the same distance ?

### ISSUE THREAD

**Issue by programistawpf** [matthieugomez/StringDistances.jl#32]
135/5000
I expected a shorter distance for Damerau Levenshtein because there is an exchange of two letters. Why are there the same results?
```
julia> compare("martha", "martht", DamerauLevenshtein())
0.8333333333333334

julia> compare("martha", "martht", Levenshtein())
0.8333333333333334

```

**Comment by matthieugomez** [comment]
The distance (`evaluate`) is one in both cases. You would find the same thing in R.

Compare is 1 -  distance /string length.
