### ISSUE TITLE
(Partial) Hamming distance

### ISSUE THREAD

**Issue by traversc** [matthieugomez/StringDistances.jl#35]
I'm looking for a function for partial hamming distance. It looks like it existed in an [earlier version](https://libraries.io/github/matthieugomez/StringDistances.jl) but was taken out. 

Is it possible to put it back in?

**Comment by matthieugomez** [comment]
Sure. Could you give a code example of what you’d like to to?

**Comment by traversc** [comment]
Something simple like:

```
compare("GACT", "CGATTGCAATGCTA", Partial(Hamming()))
```
or 
```
 findall(s, itr, Partial(Hamming()), min_score = 0.9)
```

An example use case would be as a first pass in  PCR primer design, where a hamming might be more appropriate than levenshtein or other metric.

**Comment by matthieugomez** [comment]
The issue is that `Hamming` is already defined in `Distances` and so defining it on `Strings` is type piracy.

**Comment by traversc** [comment]
I'm a bit new to Julia, but can you simply name the function something else? The name isn't important, only what it does. Something like `hammingstr` or `hamming2` etc.

**Comment by matthieugomez** [comment]
Ok, I now export a `Hamming` distance that is distinct from the one exported by `Distances`. Not super satisfied (this requires to do `StringDistances.Hamming()` when loading both `Distances` and `StringDistances`), but that's better than type piracy.
