### ISSUE TITLE
Simpler QGramDistances implementation and prep for general dictionaries and iterators

### ISSUE THREAD

**Issue by robertfeldt** [matthieugomez/StringDistances.jl#42]
Matthieu, I checked and you are right that there is little to no performance benefit in splitting the counting for QGramDistances into `countleft`, `countright`, and `countboth`. I thus made a branch which simplifies the implementation by only having a single `count` method.

I also split the helpers code for QGramDistances into separate files in a `helpers` subdir and generalized to prepare for other dictionaries (when preprocessing) as well as iterators that have varying length words (q-gram iterators are fixed length).

This new design will be more maintainable going forward and keeps the good performance. For some distances performance even improves since we need not re-calculate information we already have after preprocessing.

Even though there are no new features added there are quite a few changes so before I potentially do a PR feel free to compare to your current master here:

https://github.com/matthieugomez/StringDistances.jl/compare/master...robertfeldt:simpler_counter_design

**Comment by robertfeldt** [comment]
The simplest entrypoint might be to check how the `qgram.jl` file changed in this:

https://github.com/robertfeldt/StringDistances.jl/blob/simpler_counter_design/src/distances/qgram.jl

**Comment by matthieugomez** [comment]
That looks good. Maybe it'd be even better to remove the `_count` function, and define a `countmatches!(mc::AbstractWordMatchCounter, d1::QGramIterator, d2::QGramIterator)` method instead.

**Comment by robertfeldt** [comment]
Thanks for taking a look. Hmm, yes, but there would be no performance benefit, right, since we still need to create the full dict currently done in `_count`. Might clean up the code somewhat but not by much. I guess we might save some memory by not having to send the result from `values(d)` back but can just iterate over it. Or am I missing something? 

BTW, thanks for making me a contributor. Should I still do PRs from my forked repo or is there a simplification in the workflow? (I couldn't see what rights came with the new role).

**Comment by matthieugomez** [comment]
For the workflow, I think the idea is that you should still do PR (as I should, I need to stop committing directly), but then you can merge them by yourself (when you think it is ready, say, after a few days).

For my proposition, yes it’s just about cleaning the code a bit, not about changing performances

**Comment by matthieugomez** [comment]
Could you make a PR with your code? Maybe it's better to un-export `QGramDict` and `QgramSortedVector` (or the new names you use).  Not sure why I did that in the first place.
