### ISSUE TITLE
`Partial` only looks at substrings of the same length...

### ISSUE THREAD

**Issue by ericphanson** [matthieugomez/StringDistances.jl#43]
...but sometimes shorter substrings can give better matches:

```julia
julia> using StringDistances #v0.10

julia> a = "giant golden crowned flying fox"
"giant golden crowned flying fox"

julia> b = "A giantgolden crownedflying fox slept all day."
"A giantgolden crownedflying fox slept all day."

julia> Partial(DamerauLevenshtein())(a,b)
4

julia> DamerauLevenshtein()(a,b[3:31])
2

julia> b[3:31]
"giantgolden crownedflying fox"

```

Not really sure if this counts as a bug or not, but I think it should probably be documented at least. But if there was a performant way to match shorter subsequences too, I think that would be ideal.

**Comment by matthieugomez** [comment]
The documentation for Partial reads
"`Partial{dist}`  returns the  minimum distance  between the shorter string and substrings of the longer string that have a length equal to the shorter string."
This should be clear enough right?
