### ISSUE TITLE
Non-strings

### ISSUE THREAD

**Issue by jtrakk** [matthieugomez/StringDistances.jl#47]
I see these functions ask for `AbstractString`s. I'm curious if that is a necessary restriction, or could they also apply to `AbstractVector`s and other types?

**Comment by matthieugomez** [comment]
No, these functions do not ask for `AbstractStrings`. What made you think it was the case?

**Comment by jtrakk** [comment]
The readme says 

> Distances are defined for `AbstractStrings`

**Comment by matthieugomez** [comment]
It says 

> Distances are defined for AbstractStrings, and any iterator that define length() (e.g. graphemes, AbstractVector...)

**Comment by jtrakk** [comment]
Sorry I just misread it.
