### ISSUE TITLE
The value of "compare" is probably wrong.

### ISSUE THREAD

**Issue by C37H41N2O6** [matthieugomez/StringDistances.jl#49]
I understand that to normalize the Levenshtein distance, the value is divided by the longer string length.
However, the results I have calculated using that method are different from the results using the compare function.
```julia
julia> using StringDistances
julia> s1 = "martha"
julia> s2 = "marhtai"
julia> Levenshtein()(s1, s2)
3
julia> max(length(s1),length(s2))
7
julia> 1 - Levenshtein()(s1, s2) / 7
0.5714285714285714
julia> compare(s1, s2, Levenshtein())
0.8571428571428572
```
Why did this result occur?
I would appreciate it if you could tell me about it.

**Comment by matthieugomez** [comment]
You switched marhtai to mahrtai in your issue
