### ISSUE TITLE
Caching iterators and/or dictionary-based distances?

### ISSUE THREAD

**Issue by robertfeldt** [matthieugomez/StringDistances.jl#5]
Thanks for StringDistances.jl. For my research, I have developed a similar package and only just found yours. There is one difference in our designs in that I "cache" the Qgrams in a Counter dict so that I can later, more quickly, compare the similarity of new strings with sets of old strings. This is useful when searching/optimising for sets of similar or dissimilar strings/objects. Would you be interested in exploring a way to support this type of design also in your package?

**Comment by robertfeldt** [comment]
I actually forked StringDistances.jl and started adapting and adding my code. You can see a first commit here:

https://github.com/robertfeldt/StringDistances.jl/commit/f95c582d3848a380d0a28e92d61f664bbb70fb41

I'd be willing to submit as pull request if you think this has general value.

**Comment by matthieugomez** [comment]
Yes, that looks great. Thanks!

**Comment by matthieugomez** [comment]
Rereading the code, I kind of remember comparing the storage of qgrams as dict vs sorted vectors and concluding that sorted vectors were faster

**Comment by robertfeldt** [comment]
Ok, I will try (when back from vacation). So you mean this would be faster even for repeated pair-wise calculations? This is the use case for me. If sorted vectors not always faster I suggest a design that can use both.

**Comment by matthieugomez** [comment]
R [stringdist](https://github.com/markvanderloo/stringdist) is 4x faster for qgram on vectors. I think the reason is that it creates a binary tree structure once and for all, and then recycle it while iterating through elements of the vector.
Is your solution faster than QGram when comparing a pair of strings? When comparing a pair of `Vector{String}`?

**Comment by robertfeldt** [comment]
You are right that R's stringdist uses binary trees, see page 9 of this pdf: https://journal.r-project.org/archive/2014-1/loo.pdf

The design I propose is that we make the distance functions independent of the intermediate representation of the strings. Then we can support also binary tree versions (that seems fastest based on stringdist experience) by implementing an "importer" from AbstractString to binary tree, later. Any of the caching versions is bound to be (much) faster when comparing many Strings rather than for (repeated) one-off comparison of two strings.

**Comment by matthieugomez** [comment]
Right. That’s the current design no? I’m just using an iterator that can be created by dictionary or binary trees.
