### ISSUE TITLE
Feature Request: Parallel processing

### ISSUE THREAD

**Issue by timothyslau** [matthieugomez/StringDistances.jl#55]
I'm running `pairwise()` on two large vectors and wondered if there was a simple way to distribute this computation across multiple cores?

**Comment by matthieugomez** [comment]
This already uses multi threading
https://github.com/matthieugomez/StringDistances.jl/blob/acf6623c2d25859b51b6700ad5c70ede9aceba65/src/pairwise.jl#L55

**Comment by timothyslau** [comment]
Weird, it seemed like it was only using 1 core last night.l on my MBP.

**Comment by matthieugomez** [comment]
Maybe it’s because multicore != multithreaded. Also, be sure to start julia with multiple threads.

**Comment by timothyslau** [comment]
The multi-thread suggestion was right on the nose. Is there a way to run this on my GPU to get further speedups?
